const syllabusData = {
  "6th": {
    "Mathematics": [
      "Divisibility",
      "The Use of Letters in Place of Numbers",
      "Order of Operations and the Use of Brackets",
      "Point, Line, Plane",
      "Angles",
      "Pairs of Angles",
      "Indices",
      "Natural Numbers and Whole Numbers",
      "Decimal Fractions – Division",
      "Squares and Square Roots",
      "Ratio and Proportion",
      "Perimeter",
      "Profit and Loss",
      "Integers",
      "Equations in One Variable",
      "Algebraic Expressions",
      "Simple Interest",
      "Percentage",
      "Triangles",
      "Properties of Triangles",
      "Geometric Constructions",
      "Area",
      "Bar Graphs",
      "Volume",
      "Circle"
    ],
    "General Science": [
      "Our Natural Resources",
      "Diversity in Living Things and their Classification",
      "Disaster Management",
      "The Living World",
      "Substances in Daily Use",
      "Substances in the Surroundings – Their States and Properties",
      "Nutrition and Diet",
      "Our Skeletal System and the Skin",
      "Motion and Types of Motion",
      "Characteristics and Classification of Living Things",
      "Parts of Plants and their Structure",
      "Force and Types of Force",
      "Work and Energy",
      "Simple Machines",
      "Measurement & Estimates of Measurements",
      "Sound",
      "Methods of Separating Substances",
      "Organ Systems",
      "Our Environment",
      "Our Earth and its Special Features",
      "Social Environment"
    ]
  },
  "7th": {
    "Science": [
      "Natural Resources",
      "Water – A Natural Resource",
      "Food and Protection of Food",
      "Properties of Water",
      "Acids, Bases and Salts",
      "Control and Co-ordination",
      "Health and Disease",
      "Food and Nutrition",
      "Circulation of Blood",
      "Reproduction in Living Things",
      "The Organisation of Living Things",
      "Electric Charge",
      "Sound – Production of Sound",
      "Propagation of Sound",
      "Classification of Substances",
      "Transmission of Heat",
      "Effects of Heat",
      "Propagation of Light"
    ],
    "Maths": [
      "Indices",
      "Variation",
      "Averages",
      "Properties of Triangles",
      "Theorem of Pythagoras",
      "Construction of Triangles",
      "Equations in One Variable",
      "Product Of Algebraic Expressions",
      "Factors of Algebraic Expressions",
      "Quadrilaterals",
      "Types of Quadrilaterals",
      "Construction of Quadrilaterals",
      "Rational Numbers",
      "Operations on Rational Numbers",
      "Simple Interest",
      "Profit and Loss",
      "Area",
      "Factors of Algebraic Expressions",
      "Identity",
      "Circle",
      "Congruence",
      "Volume and Surface Area",
      "Joint Bar Graphs"
    ]
  },
  "8th": {
    "Mathematics": [
      "Irrational and Real Numbers",
      "Square and Square Root",
      "Quadrilateral",
      "Parallel Lines",
      "Area",
      "The Circle",
      "The Circumference and Area Of A Circle",
      "Statistics",
      "Identities",
      "Variation and Proportion",
      "Equations in One Variable",
      "Indices",
      "Cubes and Cube Roots",
      "Construction of Quadrilaterals",
      "Arc of a Circle",
      "Compound Interest",
      "Polynomials",
      "Joint Bar Graphs",
      "Discount and Commission",
      "Volume and Surface Area",
      "Factors of polynomials",
      "Division of Polynomials"
    ],
    "General Science": [
      "Living World and Classification of Microbes",
      "Health and Diseases",
      "Force and Pressure",
      "Current Electricity and Magnetism",
      "Inside the Atom",
      "Composition of Matter",
      "Metals and Nonmetals",
      "Pollution",
      "Disaster Management",
      "Cell and Cell Organelles",
      "Human Body and Organ System",
      "Introduction to Acid and Base",
      "Chemical Change and Chemical Bond",
      "Measurement and Effects of Heat",
      "Sound",
      "Reflection of Light",
      "Man made Materials",
      "Ecosystems",
      "Life Cycle of Stars"
    ]
  }
};

export default syllabusData;